In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3]) # initialize a one dimensional array 
arr1[0]

1

In [3]:
arr2 = np.array([[1,2],[3,4],[5,6]]) # initialize a two dimensional array
arr2[0][0]

1

In [4]:
arr2.ndim # prints no of dimensions 

2

In [5]:
arr2.itemsize # prints the byte size of each of the elements

4

In [6]:
arr2.dtype # prints current data type of the array

dtype('int32')

In [7]:
arr3 = np.array([[1,2],[3,4],[5,6]],dtype="float") # also can specifite the data type of the array while creation

In [8]:
arr3.dtype

dtype('float64')

In [9]:
arr3.size # no of elements in the array

6

In [10]:
arr3.shape # 3 rows 2 columns 

(3, 2)

In [11]:
arr4 = np.zeros((3,4)) # initilize with shape of your array

In [12]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.arange(5) # initializes an array of 5 elements starting from 0 to 4

array([0, 1, 2, 3, 4])

In [17]:
np.arange(1,13,2) # start end steps

array([ 1,  3,  5,  7,  9, 11])

In [18]:
np.linspace(1,5,50) # generate 50 numbers between 1 and 5 both inclusive

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [19]:
arr3.reshape(2,3) # reshaping the array into new dimensions 

array([[1., 2., 3.],
       [4., 5., 6.]])

In [20]:
arr3.ravel() # make a n dimentional array into 1 dimensional

array([1., 2., 3., 4., 5., 6.])

In [22]:
arr3.min() # function for minimum ele

1.0

In [23]:
arr3.max() # produces maximum ele

6.0

In [24]:
arr3.sum() # gets sum of all elements 

21.0

In [25]:
arr3

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [27]:
arr3.sum(axis=0) # sum along different axis along column

array([ 9., 12.])

In [28]:
arr3.sum(axis=1) # sum along different axis along  row

array([ 3.,  7., 11.])

In [29]:
np.sqrt(arr3) # square root of each element in the array

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [30]:
np.std(arr3) #standard deviation

1.707825127659933

In [31]:
arr3

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [32]:
arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
arr5 = arr3 + arr2
arr5

array([[ 2.,  4.],
       [ 6.,  8.],
       [10., 12.]])

In [36]:
arr2-arr3

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [37]:
arr2*arr3

array([[ 1.,  4.],
       [ 9., 16.],
       [25., 36.]])

In [38]:
arr2/arr3

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [40]:
arr2.dot(arr3.reshape(2,3)) # do matrix product in 

array([[ 9., 12., 15.],
       [19., 26., 33.],
       [29., 40., 51.]])