In [1]:
import numpy as np

In [2]:
n = np.arange(6,13)

In [3]:
n[0:2] # slice start to end

array([6, 7])

In [4]:
n[-1] # start from end

12

In [5]:
n[1:3] # start from 1st position go upto 3rd 

array([7, 8])

In [7]:
a = np.array([[6,7,8],[9,10,11],[12,13,14]])
a[1,2]

11

In [8]:
a[0,1] # first subscript tells rwo second column

7

In [9]:
a[0][1]

7

In [11]:
a

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [10]:
a[0:2,2] # go through 0 to 2 rows and print 3rd element 

array([ 8, 11])

In [12]:
a[-1]

array([12, 13, 14])

In [13]:
a[0,0:2] # in 0th row go through index 0 to 2

array([6, 7])

In [14]:
a[-1,1:3]

array([13, 14])

In [17]:
a[:,1:3] # traverse all rows and print 1 to 3 index element 

array([[ 7,  8],
       [10, 11],
       [13, 14]])

In [24]:
arr1 = np.arange(6).reshape(3,2)
arr2 = np.arange(6,12).reshape(3,2)
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [25]:
arr2

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [27]:
np.vstack((arr1,arr2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [30]:
arr3 = np.hstack((arr1,arr2))

In [35]:
for i in range(0,len(arr3)):
    for j in range(0,len(arr3[i])):
        print(arr3[i,j])
    print("\n")

0
1
6
7


2
3
8
9


4
5
10
11


